export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILED = 'GET_CATEGORIES_FAILED';

export const GET_TOPFIVESTORY = 'GET_TOPFIVESTORY';
export const GET_TOPFIVESTORY_SUCCESS = 'GET_TOPFIVESTORY_SUCCESS';
export const GET_TOPFIVESTORY_FAILED = 'GET_TOPFIVESTORY_FAILED';

export const GET_STORIES = 'GET_STORIES';
export const GET_STORIES_SUCCESS = 'GET_STORIES_SUCCESS';
export const GET_STORIES_FAILED = 'GET_STORIES_FAILED';

export const GET_NEW_STORIES = 'GET_NEW_STORIES';
export const GET_NEW_STORIES_SUCCESS = 'GET_NEW_STORIES_SUCCESS';
export const GET_NEW_STORIES_FAILED = 'GET_NEW_STORIES_FAILED';

export const GET_STORY_DETAIL = 'GET_STORY_DETAIL';
export const GET_STORY_DETAIL_SUCCESS = 'GET_STORY_DETAIL_SUCCESS';
export const GET_STORY_DETAIL_FAILED = 'GET_STORY_DETAIL_FAILED';

export const GET_CHAPTERS = 'GET_CHAPTERS';
export const GET_CHAPTERS_SUCCESS = 'GET_CHAPTERS_SUCCESS';
export const GET_CHAPTERS_FAILED = 'GET_CHAPTERS_FAILED';

export const GET_STORY_BY_AUTHOR = 'GET_STORY_BY_AUTHOR';
export const GET_STORY_BY_AUTHOR_SUCCESS = 'GET_STORY_BY_AUTHOR_SUCCESS';
export const GET_STORY_BY_AUTHOR_FAILED = 'GET_STORY_BY_AUTHOR_FAILED';

export const GET_COMMENTS = 'GET_COMMENTS';
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const GET_COMMENTS_FAILED = 'GET_COMMENTS_FAILED';

export const GET_RATINGS = 'GET_RATINGS';
export const GET_RATINGS_SUCCESS = 'GET_RATINGS_SUCCESS';
export const GET_RATINGS_FAILED = 'GET_RATINGS_FAILED';

export const GET_CHAPTER_DETAIL = 'GET_CHAPTER_DETAIL';
export const GET_CHAPTER_DETAIL_SUCCESS = 'GET_CHAPTER_DETAIL_SUCCESS';
export const GET_CHAPTER_DETAIL_FAILED = 'GET_CHAPTER_DETAIL_FAILED';

export const GET_USER_INFOR = 'GET_USER_INFOR';
export const GET_USER_INFOR_SUCCESS = 'GET_USER_INFOR_SUCCESS';
export const GET_USER_INFOR_FAILED = 'GET_USER_INFOR_FAILED';

export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const SEND_COMMENT = 'SEND_COMMENT';
export const SEND_COMMENT_SUCCESS = 'SEND_COMMENT_SUCCESS';
export const SEND_COMMENT_FAILED = 'SEND_COMMENT_FAILED';

export const RATING_STORY = 'RATING_STORY';
export const RATING_STORY_SUCCESS = 'RATING_STORY_SUCCESS';
export const RATING_STORY_FAILED = 'RATING_STORY_FAILED';

export const LIKE_STORY = 'LIKE_STORY';
export const LIKE_STORY_SUCCESS = 'LIKE_STORY_SUCCESS';
export const LIKE_STORY_FAILED = 'LIKE_STORY_FAILED';

export const LIKE_COMMENT = 'LIKE_COMMENT';
export const LIKE_COMMENT_SUCCESS = 'LIKE_COMMENT_SUCCESS';
export const LIKE_COMMENT_FAILED = 'LIKE_COMMENT_FAILED';

export const LIKE_RATING = 'LIKE_RATING';
export const LIKE_RATING_SUCCESS = 'LIKE_RATING_SUCCESS';
export const LIKE_RATING_FAILED = 'LIKE_RATING_FAILED';

export const GET_LIKE_STORY_STATUS = 'GET_LIKE_STORY_STATUS';
export const GET_LIKE_STORY_STATUS_SUCCESS = 'GET_LIKE_STORY_STATUS_SUCCESS';
export const GET_LIKE_STORY_STATUS_FAILED = 'GET_LIKE_STORY_STATUS_FAILED';

export const GET_FOLLOW_STORY_STATUS = 'GET_FOLLOW_STORY_STATUS';
export const GET_FOLLOW_STORY_STATUS_SUCCESS = 'GET_FOLLOW_STORY_STATUS_SUCCESS';
export const GET_FOLLOW_STORY_STATUS_FAILED = 'GET_FOLLOW_STORY_STATUS_FAILED';

export const FOLLOW_STORY = 'FOLLOW_STORY';
export const FOLLOW_STORY_SUCCESS = 'FOLLOW_STORY_SUCCESS';
export const FOLLOW_STORY_FAILED = 'FOLLOW_STORY_FAILED';

export const CHECK_LOGIN = 'CHECK_LOGIN';
export const CHECK_LOGIN_DONE = 'CHECK_LOGIN_DONE';

export const CHECK_LOG_OUT = 'CHECK_LOG_OUT';
export const CHECK_LOG_OUT_DONE = 'CHECK_LOG_OUT_DONE';

export const TOGGLE_AUTH_MODAL = 'TOGGLE_AUTH_MODAL';

