export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILED = 'GET_CATEGORIES_FAILED';

export const GET_TOPFIVESTORY = 'GET_TOPFIVESTORY';
export const GET_TOPFIVESTORY_SUCCESS = 'GET_TOPFIVESTORY_SUCCESS';
export const GET_TOPFIVESTORY_FAILED = 'GET_TOPFIVESTORY_FAILED';