
export const GET_MUSICS = 'GET_MUSICS';
export const GET_MUSICS_SUCCESS = 'GET_MUSICS_SUCCESS';
export const GET_MUSICS_FAILED = 'GET_MUSICS_FAILED';

export const GET_MUSICRANK = 'GET_MUSICRANK';
export const GET_MUSICRANK_SUCCESS = 'GET_MUSICRANK_SUCCESS';
export const GET_MUSICRANK_FAILED = 'GET_MUSICRANK_FAILED';

export const SELECT_MUSIC = 'SELECT_MUSIC';
export const SELECT_MUSIC_SUCCESS = 'SELECT_MUSIC_SUCCESS';
export const SELECT_MUSIC_FAILED = 'SELECT_MUSIC_FAILED';

export const GET_MUSICDETAIL = 'GET_MUSICDETAIL';
export const GET_MUSICDETAIL_SUCCESS = 'GET_MUSICDETAIL_SUCCESS';
export const GET_MUSICDETAIL_FAILED = 'GET_MUSICDETAIL_FAILED';

export const GET_ALLSONG = 'GET_ALLSONG';
export const GET_ALLSONG_SUCCESS = 'GET_ALLSONG_SUCCESS';
export const GET_ALLSONG_FAILED = 'GET_ALLSONG_FAILED';

export const GET_HOTSONGFORSLIDE = 'GET_HOTSONGFORSLIDE';
export const GET_HOTSONGFORSLIDE_SUCCESS = 'GET_HOTSONGFORSLIDE_SUCCESS';
export const GET_HOTSONGFORSLIDE_FAILED = 'GET_HOTSONGFORSLIDE_FAILED';